const englishPhrases = [
  "Access the mainframe system",
  "Bypass security protocols",
  "Download classified files",
  "Encrypt the data transmission",
  "Establish secure connection",
  "Find the hidden backdoor",
  "Generate encryption keys",
  "Hack into the network",
  "Identify vulnerable systems",
  "Jam the security signals",
  "Locate the administrator account",
  "Monitor network traffic",
  "Navigate through the firewall",
  "Obtain root privileges",
  "Penetrate the defense system",
  "Query the database records",
  "Retrieve sensitive information",
  "Scan for open ports",
  "Trace the IP address",
  "Unlock restricted access",
  "Verify authentication tokens",
  "Wipe the system logs",
  "Extract confidential documents",
  "Yield control of the server",
  "Zero in on the target system",
  "Analyze security vulnerabilities",
  "Break through the encryption",
  "Compromise the system integrity",
  "Detect intrusion attempts",
  "Evade security measures",
  "Forge access credentials",
  "Gain administrative rights",
  "Hide your digital footprint",
  "Infiltrate the secure server",
  "Jeopardize the security system",
  "Keylog the administrator actions",
  "Launch a brute force attack",
  "Manipulate system variables",
  "Neutralize security protocols",
  "Override the security system",
  "Plant a backdoor access",
  "Quantify the security risks",
  "Reverse engineer the software",
  "Sabotage the defense mechanisms",
  "Trigger the emergency protocols",
  "Undermine system stability",
  "Violate security parameters",
  "Weaponize system vulnerabilities",
  "Execute remote commands",
  "Yield sensitive information",
  "Zoom in on security flaws",
]

export function getRandomEnglishPhrase() {
  return englishPhrases[Math.floor(Math.random() * englishPhrases.length)]
}

